travis:
  secure:
    BINSTAR_TOKEN: ZkzqBbSqh5749e2Wy6QuHrm0bhncD9bmH1L3NbvT4L8NwRTRJyaqxdoSgx2DcdRddkKQZxdwYi2ocGL1NWtJaFwF6Pr7QrS7bAYMED+R5l6qg1kuTogEnJzOwnTC/GGnwrrPJmwdNzfUC1UuqXVZcRNNJCc9Mw3iQB1v4xRg/fyqqQCAzoerxt5m8ntupynWsGU0MPjkaOg9iWhTkIwo/6bk1w5pgqwBA6D5zcWUKO/aA9wzX0WN7dta9QAWPa1oYjK5zaJZSDVJq65Cm5qub52qrMjYzjxLAF5ovOdd4bjHYacBZ9OBluFFGitj01mdXGTReBN93ADf1qc5Pb48E7tp8LNfvHrTLXCC28JXb1kTmjGaAXga88X17ZWBasWjAf+4rQV+UEYvBy8tUl0AshiixQqKw/pqT0pI/WRsglhnlSOt1/h3d+QZ+twXk08nbJ4v07oIi2k0OZdtJSOnPK/L25EulzV+Bk/jOKzgE2TGk0PpRmU4Ij/nRKt07DodRoSGbqzVc5IHBeGRHbZ+8xY7zFHULwz53ATUN4192vCZDK0zDDKFQMqc8M4I0MM2+M3shQcp671yvEiA+E67+45okPJoCvKoNtJen7l4COY1UNW40j5kAWGcbc7uErNGVvsBMi2ys/27329F0shHoolKZxdHqboX97NwQjNLTWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
